# Generated by Django 4.1.7 on 2023-02-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tags_tagsarticle_article_scopes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='tagsarticle',
            options={'verbose_name': 'Связь m2m', 'verbose_name_plural': 'Связи m2m'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='tags',
            name='arcticles',
            field=models.ManyToManyField(related_name='scopes', through='articles.TagsArticle', to='articles.article'),
        ),
    ]
