# Generated by Django 4.1.7 on 2023-02-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_tags_options_alter_tagsarticle_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='arcticles',
        ),
        migrations.AlterField(
            model_name='tagsarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
    ]
